'use client'
import { useEffect,useState } from 'react'
import { ArrowLeft, Loader2, MessageCircle, RefreshCw, Trash2, Trophy, Users, Vote } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { createSupabaseBrowserClient } from '@/lib/supabase-browser'

type Row={id:string;username?:string;email?:string;message?:string;song_title?:string;song_id?:string;purpose?:string;created_at?:string;updated_at?:string;user_id?:string}
export default function LiveRoomAdmin(){const router=useRouter();const supabase=createSupabaseBrowserClient();const [data,setData]=useState<{votes:Row[];recommendations:Row[];chat:Row[]}>({votes:[],recommendations:[],chat:[]});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const load=async()=>{setBusy(true);setError('');const {data:{session}}=await supabase.auth.getSession();if(!session){router.replace('/admin/login');return}const r=await fetch('/api/admin/live-room',{headers:{authorization:`Bearer ${session.access_token}`},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)setError(d.error||'Could not load Live Room.');else setData(d);setBusy(false)};useEffect(()=>{load()},[])
 const remove=async(type:'chat'|'recommendation',id:string)=>{if(!confirm('Delete this item?'))return;const {data:{session}}=await supabase.auth.getSession();if(!session)return;await fetch('/api/admin/live-room',{method:'DELETE',headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`},body:JSON.stringify({type,id})});load()}
 const voteMap=data.votes.reduce<Record<string,number>>((a,v)=>(a[v.song_id||'']=(a[v.song_id||'']||0)+1,a),{});return <main className="min-h-screen bg-black px-5 py-12 text-white md:px-10"><div className="mx-auto max-w-6xl"><div className="flex items-center justify-between border-b border-white/10 pb-7"><div><div className="text-[9px] tracking-[.35em] text-gold">GEETQAR / LIVE ROOM CONTROL</div><h1 className="mt-3 text-4xl font-bold">Live Room</h1><p className="mt-2 text-sm text-white/35">Votes, recommendations and discussion moderation.</p></div><div className="flex gap-2"><button onClick={load} className="border border-white/10 p-3 text-white/45 hover:text-white"><RefreshCw size={15}/></button><button onClick={()=>router.push('/admin')} className="inline-flex items-center gap-2 border border-white/10 px-4 py-3 text-[10px] tracking-[.2em]"><ArrowLeft size={14}/> ADMIN</button></div></div>
 <div className="mt-8 grid gap-3 md:grid-cols-4"><div className="glass p-5"><Users size={15} className="text-gold"/><div className="mt-3 text-3xl font-bold">{new Set(data.votes.map(v=>v.user_id)).size}</div><div className="text-[9px] text-white/30">ACTIVE VOTERS</div></div><div className="glass p-5"><Vote size={15} className="text-gold"/><div className="mt-3 text-3xl font-bold">{data.votes.length}</div><div className="text-[9px] text-white/30">ACTIVE VOTES</div></div><div className="glass p-5"><Trophy size={15} className="text-gold"/><div className="mt-3 text-3xl font-bold">{Object.keys(voteMap).length}</div><div className="text-[9px] text-white/30">SONGS RECEIVING VOTES</div></div><div className="glass p-5"><MessageCircle size={15} className="text-gold"/><div className="mt-3 text-3xl font-bold">{data.chat.length}</div><div className="text-[9px] text-white/30">RECENT CHAT</div></div></div>
 {error&&<div className="mt-5 border border-red-400/20 p-4 text-xs text-red-300">{error}</div>}
 <section className="mt-8 glass p-6"><h2 className="text-xl font-semibold">Vote board</h2><p className="mt-1 text-xs text-white/30">One active vote per verified user.</p><div className="mt-5 grid gap-2">{Object.entries(voteMap).sort((a,b)=>b[1]-a[1]).map(([song,count])=><div key={song} className="flex justify-between border border-white/10 p-4"><span className="text-sm">{song}</span><span className="text-gold">{count}</span></div>)}{!Object.keys(voteMap).length&&<p className="text-xs text-white/25">No votes yet.</p>}</div></section>
 <div className="mt-8 grid gap-6 lg:grid-cols-2"><section className="glass p-6"><h2 className="text-xl font-semibold">Recommendations</h2><div className="mt-5 space-y-2">{data.recommendations.map(r=><div key={r.id} className="border border-white/10 p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-xs text-gold">{r.username} → “{r.song_title}”</div><div className="mt-2 text-sm text-white/55">{r.purpose}</div><div className="mt-2 text-[9px] text-white/25">{r.email}</div></div><button onClick={()=>remove('recommendation',r.id)} className="text-white/25 hover:text-red-300"><Trash2 size={15}/></button></div></div>)}{!data.recommendations.length&&<p className="text-xs text-white/25">No recommendations yet.</p>}</div></section><section className="glass p-6"><h2 className="text-xl font-semibold">Discussion moderation</h2><div className="mt-5 space-y-2">{data.chat.map(c=><div key={c.id} className="border border-white/10 p-4"><div className="flex items-start justify-between gap-3"><div><div className="text-xs text-gold">{c.username} <span className="text-white/25">· {c.email}</span></div><div className="mt-2 text-sm text-white/60">{c.message}</div></div><button onClick={()=>remove('chat',c.id)} className="text-white/25 hover:text-red-300"><Trash2 size={15}/></button></div></div>)}{!data.chat.length&&<p className="text-xs text-white/25">No discussion messages yet.</p>}</div></section></div>
 {busy&&<div className="fixed bottom-5 right-5 flex items-center gap-2 border border-white/10 bg-black px-4 py-3 text-xs text-white/50"><Loader2 size={14} className="animate-spin"/> Updating</div>}</div></main>}
