'use client'

import { useEffect, useState } from 'react'
import { ImagePlus, Link2, Loader2, LogOut, Pencil, Plus, Trash2, UploadCloud, X } from 'lucide-react'
import { useRouter } from 'next/navigation'
import type { UserResponse } from '@supabase/supabase-js'
import { createSupabaseBrowserClient } from '@/lib/supabase-browser'

type Song = { id:string; title:string; slug:string; youtube?:string; instagram?:string; coverUrl?:string }

export default function Admin(){
 const router=useRouter(); const supabase=createSupabaseBrowserClient()
 const [email,setEmail]=useState(''); const [songs,setSongs]=useState<Song[]>([]); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Song|null>(null); const [busy,setBusy]=useState(false); const [status,setStatus]=useState('')
 const [title,setTitle]=useState(''); const [youtube,setYoutube]=useState(''); const [instagram,setInstagram]=useState(''); const [audio,setAudio]=useState<File|null>(null); const [cover,setCover]=useState<File|null>(null)

 useEffect(()=>{let active=true; supabase.auth.getUser().then((r:UserResponse)=>{if(active)setEmail(r.data.user?.email||'')}); return()=>{active=false}},[supabase])
 useEffect(()=>{if(open)loadSongs()},[open])
 async function session(){const {data:{session}}=await supabase.auth.getSession(); if(!session?.access_token){router.replace('/admin/login');return null} return session}
 async function loadSongs(){const s=await session(); if(!s)return; const r=await fetch('/api/admin/songs',{headers:{authorization:`Bearer ${s.access_token}`},cache:'no-store'}); const d=await r.json().catch(()=>({})); if(r.ok)setSongs(d.songs||[]);else setStatus(d.error||'Could not load songs.')}
 function resetForm(){setEditing(null);setTitle('');setYoutube('');setInstagram('');setAudio(null);setCover(null);setStatus('')}
 function editSong(song:Song){setEditing(song);setTitle(song.title);setYoutube(song.youtube||'');setInstagram(song.instagram||'');setAudio(null);setCover(null);setStatus('')}
 async function uploadFile(file:File,kind:'master'|'cover',trackTitle:string,s:any){const body={fileName:file.name,kind,trackSlug:trackTitle.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')};const r=await fetch('/api/admin/upload-url',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${s.access_token}`},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not create upload URL');const {error}=await supabase.storage.from('Music').uploadToSignedUrl(d.path,d.token,file);if(error)throw error;return d.path as string}
 async function saveSong(){if(busy)return;if(!title.trim()){setStatus('Song title is required.');return}if(!editing&&!audio){setStatus('Select the WAV/FLAC master first.');return}const s=await session();if(!s)return;setBusy(true);setStatus(editing?'Saving changes…':'Uploading song…');try{let masterPath='';let coverPath='';if(audio)masterPath=await uploadFile(audio,'master',title,s);if(cover)coverPath=await uploadFile(cover,'cover',title,s);const song={id:editing?.id,title:title.trim(),youtube:youtube.trim(),instagram:instagram.trim(),...(masterPath?{masterPath}:{}),...(coverPath?{coverPath}:{})};const r=await fetch('/api/admin/songs',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${s.access_token}`},body:JSON.stringify({song})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not save song');setStatus(editing?'Song updated.':'Song uploaded.');await loadSongs();resetForm()}catch(e){setStatus(e instanceof Error?e.message:'Could not save song')}finally{setBusy(false)}}
 async function removeSong(song:Song){if(!confirm(`Delete “${song.title}” completely?`))return;const s=await session();if(!s)return;setBusy(true);try{const r=await fetch('/api/admin/songs',{method:'DELETE',headers:{'content-type':'application/json',authorization:`Bearer ${s.access_token}`},body:JSON.stringify({id:song.id})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not delete song');await loadSongs();if(editing?.id===song.id)resetForm();setStatus('Song deleted.')}catch(e){setStatus(e instanceof Error?e.message:'Could not delete song')}finally{setBusy(false)}}
 async function logout(){await supabase.auth.signOut();router.replace('/admin/login');router.refresh()}
 return <main className="min-h-screen bg-black px-6 py-24 text-white md:px-12"><div className="mx-auto max-w-4xl">
  <div className="flex items-start justify-between gap-6"><div><div className="text-[10px] tracking-[.4em] text-gold">GEETQAR / PRIVATE CONTROL</div><h1 className="mt-4 text-5xl font-bold">Artist Admin</h1><p className="mt-4 text-sm leading-7 text-white/40">Manage the complete public song catalog from here.</p></div><button onClick={logout} className="inline-flex items-center gap-2 border border-white/10 px-4 py-3 text-[10px] tracking-[.2em] text-white/50 hover:border-gold/40 hover:text-gold"><LogOut size={13}/> LOG OUT</button></div>
  {email&&<p className="mt-5 text-xs text-white/25">SIGNED IN AS {email}</p>}
  <button onClick={()=>{setOpen(v=>!v);if(open)resetForm()}} className="glass mt-10 flex w-full items-center justify-between p-7 text-left transition hover:border-gold/30"><div><div className="text-[10px] tracking-[.35em] text-gold">MUSIC LIBRARY</div><h2 className="mt-2 text-2xl font-semibold">UPLOAD SONGS</h2><p className="mt-2 text-xs text-white/35">{songs.length} song{songs.length===1?'':'s'} uploaded · click to manage</p></div><div className="flex h-12 w-12 items-center justify-center rounded-full border border-gold/40 text-gold">{open?<X size={18}/>:<Plus size={18}/>}</div></button>
  {open&&<div className="mt-6 space-y-6">
   <section className="glass p-7"><div className="flex items-center justify-between gap-4"><div><div className="text-[10px] tracking-[.35em] text-gold">{editing?'EDIT SONG':'ADD SONG'}</div><h2 className="mt-2 text-2xl font-semibold">{editing?'Edit song details':'Upload a new song'}</h2></div>{editing&&<button onClick={resetForm} className="text-xs text-white/40 hover:text-white">CANCEL</button>}</div>
    <label className="mt-7 block text-[10px] tracking-[.25em] text-white/40">SONG TITLE<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Enter the title shown on the website" className="mt-2 w-full border border-white/10 bg-black px-4 py-3 text-sm outline-none focus:border-gold/40"/></label>
    <label className="mt-5 block text-[10px] tracking-[.25em] text-white/40">MASTER AUDIO {editing&&<span className="text-white/20">(leave empty to keep current)</span>}<input className="mt-2 block w-full text-sm" type="file" accept="audio/wav,audio/x-wav,audio/flac,audio/x-flac" onChange={e=>setAudio(e.target.files?.[0]||null)}/></label>{audio&&<p className="mt-2 text-xs text-gold">Selected: {audio.name}</p>}
    <label className="mt-5 block text-[10px] tracking-[.25em] text-white/40">COVER ART {editing&&<span className="text-white/20">(leave empty to keep current)</span>}<input className="mt-2 block w-full text-sm" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setCover(e.target.files?.[0]||null)}/></label>{cover&&<p className="mt-2 text-xs text-gold">Selected: {cover.name}</p>}
    <label className="mt-5 block text-[10px] tracking-[.25em] text-white/40">YOUTUBE LINK<input value={youtube} onChange={e=>setYoutube(e.target.value)} placeholder="https://www.youtube.com/..." className="mt-2 w-full border border-white/10 bg-black px-4 py-3 text-sm outline-none focus:border-gold/40"/></label>
    <label className="mt-5 block text-[10px] tracking-[.25em] text-white/40">INSTAGRAM REEL LINK<input value={instagram} onChange={e=>setInstagram(e.target.value)} placeholder="https://www.instagram.com/reel/..." className="mt-2 w-full border border-white/10 bg-black px-4 py-3 text-sm outline-none focus:border-gold/40"/></label>
    <button onClick={saveSong} disabled={busy} className="mt-7 inline-flex items-center gap-2 border border-gold/50 px-5 py-3 text-[10px] tracking-[.25em] text-gold disabled:opacity-30">{busy?<Loader2 size={14} className="animate-spin"/>:<UploadCloud size={14}/>} {busy?'SAVING':'SAVE SONG'}</button>{status&&<p className={`mt-4 text-xs ${/error|required|invalid|failed|unauthorized/i.test(status)?'text-red-300':'text-white/45'}`}>{status}</p>}
   </section>
   <section className="glass p-7"><div className="flex items-end justify-between gap-4"><div><div className="text-[10px] tracking-[.35em] text-gold">UPLOADED SONGS</div><h2 className="mt-2 text-2xl font-semibold">Your catalog · {songs.length}</h2></div><button onClick={()=>{resetForm();window.scrollTo({top:0,behavior:'smooth'})}} className="inline-flex items-center gap-2 border border-white/10 px-4 py-3 text-[10px] tracking-[.2em] text-white/60 hover:border-gold/30 hover:text-gold"><Plus size={13}/> ADD SONG</button></div>
    {songs.length===0?<p className="mt-8 text-sm text-white/35">No songs uploaded yet.</p>:<div className="mt-7 space-y-3">{songs.map((song,i)=><div key={song.id} className="flex items-center gap-4 border border-white/10 p-3"><div className="h-14 w-14 shrink-0 overflow-hidden border border-gold/20 bg-black/40">{song.coverUrl?<img src={song.coverUrl} alt="" className="h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-xs text-gold">{String(i+1).padStart(2,'0')}</div>}</div><div className="min-w-0 flex-1"><div className="truncate font-semibold">{song.title}</div><div className="mt-1 text-[10px] text-white/30">{song.youtube?'YouTube · ':''}{song.instagram?'Instagram Reel':''}</div></div><button onClick={()=>editSong(song)} className="border border-white/10 p-3 text-white/50 hover:border-gold/30 hover:text-gold" aria-label="Edit"><Pencil size={14}/></button><button onClick={()=>removeSong(song)} className="border border-white/10 p-3 text-white/50 hover:border-red-400/40 hover:text-red-300" aria-label="Delete"><Trash2 size={14}/></button></div>)}</div>}
   </section>
  </div>}
 </div></main>
}
