'use client'
import {useEffect,useState} from 'react'
import {Loader2,LogOut,Pencil,Plus,Star,Trash2,UploadCloud,X} from 'lucide-react'
import {useRouter} from 'next/navigation'
import type {UserResponse} from '@supabase/supabase-js'
import {createSupabaseBrowserClient} from '@/lib/supabase-browser'
type Song={id:string;title:string;slug:string;youtube?:string;instagram?:string;coverUrl?:string;featured?:boolean}
export default function Admin(){const router=useRouter(),supabase=createSupabaseBrowserClient();const[email,setEmail]=useState(''),[songs,setSongs]=useState<Song[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Song|null>(null),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[title,setTitle]=useState(''),[youtube,setYoutube]=useState(''),[instagram,setInstagram]=useState(''),[featured,setFeatured]=useState(false),[audio,setAudio]=useState<File|null>(null),[cover,setCover]=useState<File|null>(null)
useEffect(()=>{let a=true;supabase.auth.getUser().then((r:UserResponse)=>{if(a)setEmail(r.data.user?.email||'')});return()=>{a=false}},[supabase]);useEffect(()=>{if(open)loadSongs()},[open])
async function session(){const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token){router.replace('/admin/login');return null}return session}
async function loadSongs(){const s=await session();if(!s)return;const r=await fetch('/api/admin/songs',{headers:{authorization:`Bearer ${s.access_token}`},cache:'no-store'}),d=await r.json().catch(()=>({}));if(r.ok)setSongs(d.songs||[]);else setStatus(d.error||'Could not load songs.')}
function reset(){setEditing(null);setTitle('');setYoutube('');setInstagram('');setFeatured(false);setAudio(null);setCover(null);setStatus('')}
function edit(s:Song){setEditing(s);setTitle(s.title);setYoutube(s.youtube||'');setInstagram(s.instagram||'');setFeatured(s.featured===true);setAudio(null);setCover(null);setStatus('')}
async function upload(file:File,kind:'master'|'cover',t:string,s:any){const body={fileName:file.name,kind,trackSlug:t.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')},r=await fetch('/api/admin/upload-url',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${s.access_token}`},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not create upload URL');const{error}=await supabase.storage.from('Music').uploadToSignedUrl(d.path,d.token,file);if(error)throw error;return d.path}
async function save(){if(busy)return;if(!title.trim()){setStatus('Song title is required.');return}if(!editing&&!audio){setStatus('Select the WAV/FLAC master first.');return}const s=await session();if(!s)return;setBusy(true);try{const masterPath=audio?await upload(audio,'master',title,s):'',coverPath=cover?await upload(cover,'cover',title,s):'',song={id:editing?.id,title:title.trim(),youtube:youtube.trim(),instagram:instagram.trim(),featured,...(masterPath?{masterPath}:{}),...(coverPath?{coverPath}:{})},r=await fetch('/api/admin/songs',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${s.access_token}`},body:JSON.stringify({song})}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Could not save song');await loadSongs();reset();setStatus('Saved.')}catch(e){setStatus(e instanceof Error?e.message:'Could not save song')}finally{setBusy(false)}}
async function toggle(s:Song){const a=await session();if(!a)return;setBusy(true);try{const r=await fetch('/api/admin/songs',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${a.access_token}`},body:JSON.stringify({song:{id:s.id,title:s.title,featured:!s.featured}})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not update feature');await loadSongs()}catch(e){setStatus(e instanceof Error?e.message:'Could not update feature')}finally{setBusy(false)}}
async function remove(s:Song){if(!confirm(`Delete “${s.title}” completely?`))return;const a=await session();if(!a)return;setBusy(true);try{const r=await fetch('/api/admin/songs',{method:'DELETE',headers:{'content-type':'application/json',authorization:`Bearer ${a.access_token}`},body:JSON.stringify({id:s.id})});if(!r.ok)throw new Error('Could not delete song');await loadSongs();if(editing?.id===s.id)reset()}finally{setBusy(false)}}
async function logout(){await supabase.auth.signOut();router.replace('/admin/login');router.refresh()}
return <main className="min-h-screen bg-black px-6 py-24 text-white md:px-12"><div className="mx-auto max-w-5xl"><div className="flex items-start justify-between"><div><div className="text-[10px] tracking-[.4em] text-gold">GEETQAR / PRIVATE CONTROL</div><h1 className="mt-4 text-5xl font-bold">Artist Admin</h1><p className="mt-4 text-sm text-white/40">Your music control room.</p></div><button onClick={logout} className="border border-white/10 p-3"><LogOut size={14}/></button></div>{email&&<p className="mt-4 text-xs text-white/25">SIGNED IN AS {email}</p>}
<button onClick={()=>{setOpen(v=>!v);if(open)reset()}} className="glass mt-10 flex w-full items-center justify-between p-7 text-left"><div><div className="text-[10px] tracking-[.35em] text-gold">MUSIC LIBRARY</div><h2 className="mt-2 text-2xl font-semibold">UPLOAD SONGS</h2><p className="mt-2 text-xs text-white/35">{songs.length} total · {songs.filter(s=>s.featured).length} featured in The Sounds</p></div>{open?<X/>:<Plus/>}</button>
{open&&<div className="mt-6 space-y-6"><section className="glass p-7"><div className="flex justify-between"><div><div className="text-[10px] tracking-[.35em] text-gold">{editing?'EDIT SONG':'ADD SONG'}</div><h2 className="mt-2 text-2xl">{editing?'Edit song':'Upload a new song'}</h2></div>{editing&&<button onClick={reset}>CANCEL</button>}</div><label className="mt-6 block text-[10px] tracking-[.2em] text-white/40">SONG TITLE<input value={title} onChange={e=>setTitle(e.target.value)} className="mt-2 w-full border border-white/10 bg-black p-3" placeholder="Title shown on website"/></label><label className="mt-4 block text-[10px] tracking-[.2em] text-white/40">MASTER AUDIO<input className="mt-2 block" type="file" accept="audio/wav,audio/x-wav,audio/flac,audio/x-flac" onChange={e=>setAudio(e.target.files?.[0]||null)}/></label><label className="mt-4 block text-[10px] tracking-[.2em] text-white/40">COVER ART<input className="mt-2 block" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setCover(e.target.files?.[0]||null)}/></label><label className="mt-4 block text-[10px] tracking-[.2em] text-white/40">YOUTUBE<input value={youtube} onChange={e=>setYoutube(e.target.value)} className="mt-2 w-full border border-white/10 bg-black p-3"/></label><label className="mt-4 block text-[10px] tracking-[.2em] text-white/40">INSTAGRAM REEL<input value={instagram} onChange={e=>setInstagram(e.target.value)} className="mt-2 w-full border border-white/10 bg-black p-3"/></label><label className="mt-5 flex cursor-pointer items-center gap-3 border border-gold/20 p-4"><input type="checkbox" checked={featured} onChange={e=>setFeatured(e.target.checked)}/><span><b className="text-sm">Feature in The Sounds</b><small className="block text-xs text-white/35">Only selected songs appear in the main featured section.</small></span></label><button onClick={save} disabled={busy} className="mt-6 inline-flex items-center gap-2 border border-gold/40 px-5 py-3 text-[10px] tracking-[.2em] text-gold">{busy?<Loader2 className="animate-spin" size={14}/>:<UploadCloud size={14}/>} SAVE SONG</button>{status&&<p className="mt-3 text-xs text-white/50">{status}</p>}</section>
<section className="glass p-7"><div className="flex items-center justify-between"><div><div className="text-[10px] tracking-[.35em] text-gold">CATALOGUE / ALL SONGS</div><h2 className="mt-2 text-2xl">{songs.length} songs</h2></div><button onClick={()=>{reset();window.scrollTo({top:0,behavior:'smooth'})}}><Plus/></button></div><div className="mt-6 space-y-3">{songs.map((s,i)=><div key={s.id} className="flex items-center gap-3 border border-white/10 p-3"><div className="flex h-12 w-12 items-center justify-center overflow-hidden border border-gold/20">{s.coverUrl?<img src={s.coverUrl} className="h-full w-full object-cover" alt=""/>:<span className="text-xs text-gold">{String(i+1).padStart(2,'0')}</span>}</div><div className="min-w-0 flex-1"><div className="truncate font-semibold">{s.title}</div><div className="text-[9px] text-white/30">{s.featured?'FEATURED · THE SOUNDS':'CATALOGUE ONLY'}</div></div><button title="Feature toggle" onClick={()=>toggle(s)} className={s.featured?'text-gold':'text-white/25'}><Star size={17} fill={s.featured?'currentColor':'none'}/></button><button onClick={()=>edit(s)} className="text-white/40"><Pencil size={15}/></button><button onClick={()=>remove(s)} className="text-white/40"><Trash2 size={15}/></button></div>)}</div></section></div>}</div></main>}
