import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
const BUCKET='Music', META_PATH='config/songs.json'
type Song={id:string;title:string;slug:string;masterPath:string;coverPath?:string;youtube?:string;instagram?:string;description?:string;featured?:boolean;createdAt:string;updatedAt:string}
function config(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,anonKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY,adminEmail=process.env.GEETQAR_ADMIN_EMAIL?.trim().toLowerCase();if(!url||!anonKey||!serviceKey||!adminEmail)return null;return{url,anonKey,serviceKey,adminEmail}}
async function requireAdmin(req:Request){const cfg=config();if(!cfg)return{error:NextResponse.json({error:'Admin storage is not configured.'},{status:503})};const token=(req.headers.get('authorization')||'').replace(/^Bearer /,'');if(!token)return{error:NextResponse.json({error:'Authentication required.'},{status:401})};const c=createClient(cfg.url,cfg.anonKey,{auth:{persistSession:false}});const {data:{user},error}=await c.auth.getUser(token);if(error||!user||user.email?.toLowerCase()!==cfg.adminEmail)return{error:NextResponse.json({error:'Unauthorized.'},{status:401})};return{cfg}}
function slugify(v:string){return v.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)}
async function readSongs(db:any):Promise<Song[]>{const {data}=await db.storage.from(BUCKET).download(META_PATH);if(!data)return[];try{const p=JSON.parse(await data.text());return Array.isArray(p?.songs)?p.songs as Song[]:[]}catch{return[]}}
async function writeSongs(db:any,songs:Song[]){const {error}=await db.storage.from(BUCKET).upload(META_PATH,Buffer.from(JSON.stringify({songs},null,2),'utf8'),{contentType:'application/json',upsert:true});return error}
async function withCoverUrls(db:any,songs:Song[]){return Promise.all(songs.map(async s=>{let coverUrl='';if(s.coverPath){const x=await db.storage.from(BUCKET).createSignedUrl(s.coverPath,3600);coverUrl=x.data?.signedUrl||''}return{...s,coverUrl,masterPath:undefined,coverPath:undefined}}))}
export async function GET(req:Request){const a=await requireAdmin(req);if('error'in a)return a.error;const db=createClient(a.cfg.url,a.cfg.serviceKey,{auth:{persistSession:false}});return NextResponse.json({songs:await withCoverUrls(db,await readSongs(db))},{headers:{'Cache-Control':'no-store'}})}
export async function POST(req:Request){const a=await requireAdmin(req);if('error'in a)return a.error;const b=await req.json().catch(()=>null),i=b?.song,id=typeof i?.id==='string'&&i.id.trim()?i.id.trim():crypto.randomUUID(),title=typeof i?.title==='string'?i.title.trim():'',masterPath=typeof i?.masterPath==='string'?i.masterPath.trim():'',coverPath=typeof i?.coverPath==='string'?i.coverPath.trim():'',featured=Boolean(i?.featured);if(!title||title.length>120)return NextResponse.json({error:'Song title is required.'},{status:400});const db=createClient(a.cfg.url,a.cfg.serviceKey,{auth:{persistSession:false}}),songs=await readSongs(db),idx=songs.findIndex(s=>s.id===id),old=idx>=0?songs[idx]:null;const youtube=typeof i?.youtube==='string'?i.youtube.trim():(old?.youtube||''),instagram=typeof i?.instagram==='string'?i.instagram.trim():(old?.instagram||''),description=typeof i?.description==='string'?i.description.trim():(old?.description||'');if(description.length>500)return NextResponse.json({error:'Description is too long.'},{status:400});if(masterPath&&!masterPath.startsWith('masters/'))return NextResponse.json({error:'Invalid master file.'},{status:400});if(coverPath&&!coverPath.startsWith('covers/'))return NextResponse.json({error:'Invalid artwork file.'},{status:400});if(!/^$|https:\/\/(www\.)?(youtube\.com|youtu\.be)\//i.test(youtube))return NextResponse.json({error:'YouTube link is invalid.'},{status:400});if(!/^$|https:\/\/(www\.)?instagram\.com\//i.test(instagram))return NextResponse.json({error:'Instagram link is invalid.'},{status:400});const now=new Date().toISOString(),slug=slugify(title)||`song-${id.slice(0,8)}`;if(songs.some(s=>s.id!==id&&s.slug===slug))return NextResponse.json({error:'A song with this title already exists.'},{status:409});if(!old&&!masterPath)return NextResponse.json({error:'Upload the master audio first.'},{status:400});const song:Song={id,title,slug,masterPath:masterPath||old?.masterPath||'',coverPath:coverPath||old?.coverPath,youtube,instagram,description,featured:typeof i?.featured==='boolean'?featured:(old?.featured??false),createdAt:old?.createdAt||now,updatedAt:now};if(idx>=0)songs[idx]=song;else songs.push(song);const e=await writeSongs(db,songs);if(e)return NextResponse.json({error:e.message},{status:500});if(old?.masterPath&&masterPath&&old.masterPath!==masterPath)await db.storage.from(BUCKET).remove([old.masterPath]);if(old?.coverPath&&coverPath&&old.coverPath!==coverPath)await db.storage.from(BUCKET).remove([old.coverPath]);return NextResponse.json({ok:true,song})}
export async function DELETE(req:Request){const a=await requireAdmin(req);if('error'in a)return a.error;const b=await req.json().catch(()=>null),id=typeof b?.id==='string'?b.id.trim():'';if(!id)return NextResponse.json({error:'Song id is required.'},{status:400});const db=createClient(a.cfg.url,a.cfg.serviceKey,{auth:{persistSession:false}}),songs=await readSongs(db),song=songs.find(s=>s.id===id);if(!song)return NextResponse.json({error:'Song not found.'},{status:404});const e=await writeSongs(db,songs.filter(s=>s.id!==id));if(e)return NextResponse.json({error:e.message},{status:500});const paths=[song.masterPath,song.coverPath].filter(Boolean) as string[];if(paths.length)await db.storage.from(BUCKET).remove(paths);return NextResponse.json({ok:true})}
