'use client'

import { motion } from 'framer-motion'
import { ArrowDown, Instagram, Play, Youtube } from 'lucide-react'
import { AudioVisualizer } from '@/components/audio-visualizer'

const tracks = [{id:'velvet-play',title:'VELVET PLAY',meta:'Seductive R&B · 2026'},{id:'stolen-from-the-dreams',title:'STOLEN FROM THE DREAMS',meta:'Soul · 2026'}]

export default function Home(){return <main className="min-h-screen overflow-hidden">
  <nav className="fixed top-0 z-40 flex w-full items-center justify-between px-6 py-6 md:px-12"><div className="text-sm tracking-[.5em] font-semibold">GEETQAR</div><div className="hidden gap-8 text-[10px] tracking-[.28em] text-white/60 md:flex"><a href="#music">MUSIC</a><a href="#arena">ARENA</a><a href="#about">ABOUT</a></div><div className="flex gap-3"><a aria-label="Instagram" href="https://www.instagram.com/geetqar/" target="_blank"><Instagram size={16}/></a><a aria-label="YouTube" href="https://www.youtube.com/@geetqar" target="_blank"><Youtube size={16}/></a></div></nav>
  <section className="relative flex min-h-screen items-center px-6 md:px-12"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_45%,rgba(212,175,55,.13),transparent_32%),radial-gradient(circle_at_20%_80%,rgba(255,255,255,.04),transparent_25%)]"/><motion.div initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{duration:1}} className="relative max-w-5xl pt-20"><p className="mb-6 text-[10px] tracking-[.5em] text-gold">WRITER · COMPOSER · PRODUCER</p><h1 className="text-[16vw] font-extrabold leading-[.78] tracking-[-.08em] md:text-[11vw]">GEET<span className="gold-text">QAR</span></h1><p className="mt-10 max-w-xl text-sm leading-7 text-white/50 md:text-base">Music made in the spaces between thought, desire and memory.</p><a href="#music" className="mt-10 inline-flex items-center gap-3 border border-gold/40 px-6 py-3 text-[10px] tracking-[.3em] text-gold transition hover:bg-gold hover:text-black"><Play size={13} fill="currentColor"/> ENTER THE SOUND</a></motion.div><ArrowDown className="absolute bottom-8 left-1/2 animate-bounce text-gold/70" size={18}/></section>
  <section id="music" className="border-t border-white/10 px-6 py-24 md:px-12 md:py-32"><div className="mb-12 flex items-end justify-between"><div><p className="text-[10px] tracking-[.4em] text-gold">01 / THE CATALOG</p><h2 className="mt-3 text-4xl font-semibold tracking-tight md:text-6xl">The sound.</h2></div><span className="hidden text-[10px] text-white/30 md:block">ORIGINAL MASTERS · PRIVATE ARCHIVE</span></div><div className="grid gap-4">{tracks.map((track,i)=><motion.article key={track.id} whileHover={{x:8}} className="glass group flex items-center gap-5 p-5 md:p-7"><div className="flex h-16 w-16 items-center justify-center border border-gold/20 text-gold"><span className="text-xs">0{i+1}</span></div><div className="flex-1"><h3 className="font-semibold tracking-wide">{track.title}</h3><p className="mt-1 text-xs text-white/35">{track.meta}</p></div><button className="flex h-12 w-12 items-center justify-center rounded-full border border-gold/30 text-gold transition group-hover:bg-gold group-hover:text-black"><Play size={16} fill="currentColor"/></button></motion.article>)}</div><div className="mt-12"><AudioVisualizer/></div></section>
  <section id="arena" className="px-6 py-24 md:px-12 md:py-32"><p className="text-[10px] tracking-[.4em] text-gold">02 / COMMUNITY</p><div className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><div className="glass p-7 md:p-10"><span className="text-[9px] tracking-[.35em] text-gold">PINNED BY GEETQAR</span><h2 className="mt-6 text-3xl font-semibold md:text-5xl">What does a song become after it becomes yours?</h2><p className="mt-6 max-w-2xl text-sm leading-7 text-white/45">Share your POV, review a track, or start a conversation around the music. Every discussion stays attached to the song that inspired it.</p><button className="mt-8 border border-white/15 px-5 py-3 text-[10px] tracking-[.25em] transition hover:border-gold hover:text-gold">ENTER THE ARENA</button></div><div className="glass flex min-h-64 flex-col justify-between p-7"><div><span className="text-[9px] tracking-[.35em] text-white/35">LIVE JUKEBOX</span><h3 className="mt-4 text-2xl">Vote what plays next.</h3></div><p className="text-xs leading-6 text-white/40">Pick a Geetqar track, upvote the queue and watch the room decide.</p></div></div></section>
  <footer id="about" className="border-t border-white/10 px-6 py-16 md:px-12"><div className="flex flex-col justify-between gap-8 md:flex-row"><div><p className="text-3xl font-bold tracking-[-.04em]">GEETQAR</p><p className="mt-3 text-xs text-white/30">Music beyond sound.</p></div><div className="flex gap-5 text-white/45"><a href="https://www.instagram.com/geetqar/" target="_blank"><Instagram size={18}/></a><a href="https://www.youtube.com/@geetqar" target="_blank"><Youtube size={18}/></a></div></div></footer>
</main>}