'use client'
import { motion } from 'framer-motion'
import { ArrowDown, Instagram, Youtube, Play, ExternalLink, MessageCircle } from 'lucide-react'
import { AudioVisualizer } from '@/components/audio-visualizer'
import { MusicPlayer } from '@/components/music-player'
import { Jukebox } from '@/components/jukebox'
import { Recommendations } from '@/components/recommendations'
import { GeetqarLab } from '@/components/geetqar-lab'
import { useCallback, useEffect, useState } from 'react'

type Song={id:string;title:string;slug:string;youtube?:string;instagram?:string;coverUrl?:string}

export default function Home(){
 const [selected,setSelected]=useState<Song|null>(null)
 const [songs,setSongs]=useState<Song[]>([])
 const [covers,setCovers]=useState<Record<string,string>>({})
 useEffect(()=>{fetch('/api/songs',{cache:'no-store'}).then(r=>r.ok?r.json():{songs:[]}).then(d=>{const list=d.songs||[];setSongs(list);setCovers(Object.fromEntries(list.filter((s:Song)=>s.coverUrl).map((s:Song)=>[s.title,s.coverUrl!])))}).catch(()=>{})},[])
 const handleCover=useCallback((track:string,url:string)=>{if(url)setCovers(prev=>prev[track]===url?prev:{...prev,[track]:url})},[])
 const tracks=songs.map(s=>s.title)
 return <main className="min-h-screen overflow-hidden">
 <nav className="fixed top-0 z-40 flex w-full items-center justify-between px-6 py-6 md:px-12"><a href="#top" className="text-sm font-semibold tracking-[.5em]">GEETQAR</a><div className="hidden gap-8 text-[10px] tracking-[.28em] text-white/60 md:flex"><a href="#music">MUSIC</a><a href="#jukebox">JUKEBOX</a><a href="#recommend">RECOMMEND</a><a href="#arena">ARENA</a></div><div className="flex gap-3"><a href="https://www.instagram.com/geetqar/" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={16}/></a><a href="https://www.youtube.com/@geetqar" target="_blank" rel="noreferrer" aria-label="YouTube"><Youtube size={16}/></a></div></nav>
 <section id="top" className="relative flex min-h-screen items-center px-6 md:px-12"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_45%,rgba(212,175,55,.13),transparent_32%),radial-gradient(circle_at_20%_80%,rgba(255,255,255,.04),transparent_25%)]"/><motion.div initial={{opacity:0,y:35}} animate={{opacity:1,y:0}} transition={{duration:1}} className="relative max-w-5xl pt-20"><p className="mb-6 text-[10px] tracking-[.5em] text-gold">WRITER · COMPOSER · PRODUCER</p><h1 className="text-[16vw] font-extrabold leading-[.78] tracking-[-.08em] md:text-[11vw]">GEET<span className="gold-text">QAR</span></h1><p className="mt-10 max-w-xl text-sm leading-7 text-white/50 md:text-base">Music made in the spaces between thought, desire and memory.</p><a href="#music" className="mt-10 inline-flex items-center gap-3 border border-gold/40 px-6 py-3 text-[10px] tracking-[.3em] text-gold transition hover:bg-gold hover:text-black"><Play size={13} fill="currentColor"/> ENTER THE SOUND</a></motion.div><ArrowDown className="absolute bottom-8 left-1/2 animate-bounce text-gold/70" size={18}/></section>
 <GeetqarLab/>
 <section id="music" className="border-t border-white/10 px-6 py-24 md:px-12 md:py-32"><p className="text-[10px] tracking-[.4em] text-gold">01 / THE CATALOG</p><h2 className="mt-3 text-4xl font-semibold md:text-6xl">The sound.</h2><div className="mt-10 grid gap-4">{songs.map((song,i)=><motion.div key={song.id} whileHover={{x:8}} className="glass cursor-pointer p-5 md:p-7" onClick={()=>setSelected(song)}><div className="mb-5 flex items-center gap-4"><div className="h-12 w-12 shrink-0 overflow-hidden border border-gold/20 bg-black/40">{covers[song.title]?<img src={covers[song.title]} alt={`${song.title} artwork`} className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center text-xs text-gold">{String(i+1).padStart(2,'0')}</div>}</div><div className="flex-1"><h3 className="font-semibold">{song.title}</h3><p className="text-xs text-white/35">Original Geetqar master</p></div><ExternalLink size={15} className="text-white/30"/></div><MusicPlayer title={song.title} onCover={url=>handleCover(song.title,url)}/></motion.div>)}{songs.length===0&&<div className="glass p-8 text-sm text-white/35">No songs in the catalog yet.</div>}</div><div className="mt-10"><AudioVisualizer/></div></section>
 <section id="jukebox" className="border-t border-white/10 px-6 py-24 md:px-12"><p className="text-[10px] tracking-[.4em] text-gold">02 / LIVE ROOM</p><h2 className="mt-3 text-4xl font-semibold md:text-6xl">The Jukebox.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/40">The room decides what plays next. Add a track, upvote it, and talk while it climbs the queue.</p><div className="mt-10"><Jukebox tracks={tracks}/></div></section>
 <section id="recommend" className="border-t border-white/10 px-6 py-24 md:px-12"><p className="text-[10px] tracking-[.4em] text-gold">03 / THE REQUEST LINE</p><h2 className="mt-3 text-4xl font-semibold md:text-6xl">Recommend a song.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-white/40">Send a song, point to the part that matters, and leave your reason. The best recommendations become part of the listening archive.</p><div className="mt-10"><Recommendations/></div></section>
 <section id="arena" className="border-t border-white/10 px-6 py-24 md:px-12"><p className="text-[10px] tracking-[.4em] text-gold">04 / DISCUSSION ARENA</p><div className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><div className="glass p-7 md:p-10"><span className="text-[9px] tracking-[.35em] text-gold">PINNED BY GEETQAR</span><h2 className="mt-6 text-3xl font-semibold md:text-5xl">What does a song become after it becomes yours?</h2><p className="mt-6 max-w-2xl text-sm leading-7 text-white/45">Share your POV, review a track, or start a conversation around the music.</p><a href="#jukebox" className="mt-8 inline-flex items-center gap-2 border border-white/15 px-5 py-3 text-[10px] tracking-[.25em] transition hover:border-gold hover:text-gold"><MessageCircle size={13}/> ENTER THE ARENA</a></div><div className="glass flex min-h-64 flex-col justify-between p-7"><div><span className="text-[9px] tracking-[.35em] text-white/35">PRIVATE ARCHIVE</span><h3 className="mt-4 text-2xl">Original masters.</h3></div><p className="text-xs leading-6 text-white/40">Uncompressed WAV/FLAC files stay behind private signed URLs.</p></div></div></section>
 <footer className="border-t border-white/10 px-6 py-16 md:px-12"><div className="flex justify-between"><div><p className="text-3xl font-bold">GEETQAR</p><p className="mt-3 text-xs text-white/30">Music beyond sound.</p></div><div className="flex gap-5 text-white/45"><a href="https://www.instagram.com/geetqar/" target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram size={18}/></a><a href="https://www.youtube.com/@geetqar" target="_blank" rel="noreferrer" aria-label="YouTube"><Youtube size={18}/></a></div></div></footer>
 {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-6 backdrop-blur-md" onClick={()=>setSelected(null)}><div className="glass w-full max-w-2xl p-7 md:p-10" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between"><div><span className="text-[9px] tracking-[.35em] text-gold">GEETQAR / TRACK</span><h2 className="mt-3 text-3xl font-bold md:text-5xl">{selected.title}</h2></div><button onClick={()=>setSelected(null)} className="text-white/40 hover:text-white">CLOSE</button></div>{covers[selected.title]&&<img src={covers[selected.title]} alt={`${selected.title} artwork`} className="mt-6 aspect-video w-full rounded-sm object-cover"/>}<p className="mt-5 text-sm leading-7 text-white/45">Original Geetqar composition. Listen to the master or follow the song wherever it lives.</p><div className="mt-7"><MusicPlayer title={selected.title} onCover={url=>handleCover(selected.title,url)}/></div><div className="mt-6 flex flex-wrap gap-3">{selected.youtube&&<a href={selected.youtube} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-gold/30 px-4 py-3 text-[10px] tracking-[.2em] text-gold"><Youtube size={14}/> YOUTUBE</a>}{selected.instagram&&<a href={selected.instagram} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-white/10 px-4 py-3 text-[10px] tracking-[.2em]"><Instagram size={14}/> INSTAGRAM REEL</a>}</div></div></div>}
 </main>
}
