'use client'
import { useEffect, useState } from 'react'
import { Search, Play, Plus, Loader2, Clock3, MessageCircle, X, Link as LinkIcon } from 'lucide-react'
import { supabase } from '@/lib/queue'

type Result={id:string;title:string;channel:string;description:string;thumbnail?:string}
type Recommendation={id:string;youtube_id:string;title:string;channel:string;thumbnail?:string;username:string;comment:string;start_seconds:number;end_seconds:number;created_at:string}

function seconds(v:string){const n=Number(v);return Number.isFinite(n)&&n>=0?Math.min(Math.floor(n),3600):0}
function youtubeId(value:string){try{const u=new URL(value.trim());if(u.hostname.includes('youtu.be')) return u.pathname.slice(1).split('/')[0]||null;if(u.hostname.includes('youtube.com')) return u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).pop()||null}catch{}return null}

export function Recommendations(){
 const [query,setQuery]=useState(''); const [url,setUrl]=useState(''); const [results,setResults]=useState<Result[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [selected,setSelected]=useState<Result|null>(null); const [name,setName]=useState(''); const [comment,setComment]=useState(''); const [start,setStart]=useState(''); const [end,setEnd]=useState(''); const [saving,setSaving]=useState(false); const [items,setItems]=useState<Recommendation[]>([])
 const search=async()=>{const q=query.trim();if(q.length<2)return;setLoading(true);setError('');try{const r=await fetch(`/api/youtube/search?q=${encodeURIComponent(q)}`);const d=await r.json();if(!r.ok)throw new Error(d.error||'Search failed');setResults(d.items||[])}catch(e){setError(e instanceof Error?e.message:'Search failed')}finally{setLoading(false)}}
 const addUrl=async()=>{const id=youtubeId(url);if(!id){setError('Paste a valid YouTube video URL.');return}setLoading(true);setError('');try{const r=await fetch(`https://www.youtube.com/oembed?url=${encodeURIComponent(`https://www.youtube.com/watch?v=${id}`)}&format=json`);if(!r.ok)throw new Error('Could not read that YouTube video.');const d=await r.json();setSelected({id,title:d.title||'YouTube video',channel:d.author_name||'YouTube',description:'',thumbnail:d.thumbnail_url||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`});setUrl('')}catch(e){setError(e instanceof Error?e.message:'Could not read YouTube URL')}finally{setLoading(false)}}
 useEffect(()=>{const db=supabase();const load=async()=>{const {data,error}=await db.from('song_recommendations').select('*').order('created_at',{ascending:false}).limit(50);if(error)setError(error.message);else setItems((data||[]) as Recommendation[])};load();const ch=db.channel('geetqar-recommendations').on('postgres_changes',{event:'INSERT',schema:'public',table:'song_recommendations'},p=>setItems(x=>[p.new as Recommendation,...x].slice(0,50))).subscribe();return()=>{db.removeChannel(ch)}},[])
 const save=async()=>{if(!selected)return;const username=name.trim();const text=comment.trim();if(username.length<2||username.length>24||text.length>1000||saving)return;setSaving(true);setError('');const {error:e}=await supabase().from('song_recommendations').insert({youtube_id:selected.id,title:selected.title,channel:selected.channel,thumbnail:selected.thumbnail,username,comment:text,start_seconds:seconds(start),end_seconds:seconds(end)});if(e)setError(e.message);else{setSelected(null);setComment('');setStart('');setEnd('')}setSaving(false)}
 return <div className="grid gap-6 lg:grid-cols-[1.05fr_.95fr]">
  <div className="glass p-6 md:p-8">
   <div className="flex items-center justify-between"><div><span className="text-[9px] tracking-[.35em] text-gold">COMMUNITY RECOMMENDATIONS</span><h3 className="mt-2 text-2xl font-semibold">Tell Geetqar what to hear.</h3></div><MessageCircle className="text-gold/70" size={18}/></div>
   <p className="mt-3 text-xs leading-6 text-white/40">Search YouTube when the free API is configured, or paste any YouTube link without a Google API key.</p>
   <div className="mt-6 flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Search any song… e.g. Winning Speech" className="min-w-0 flex-1 border border-white/10 bg-transparent px-4 py-3 text-sm outline-none focus:border-gold"/><button onClick={search} disabled={loading||query.trim().length<2} className="flex h-12 w-12 shrink-0 items-center justify-center border border-gold/30 text-gold hover:bg-gold hover:text-black disabled:opacity-30">{loading?<Loader2 className="animate-spin" size={17}/>:<Search size={17}/>}</button></div>
   <div className="mt-3 flex gap-2"><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addUrl()} placeholder="Or paste a YouTube link…" className="min-w-0 flex-1 border border-white/10 bg-transparent px-4 py-3 text-xs outline-none focus:border-gold"/><button onClick={addUrl} disabled={loading||!url.trim()} className="flex items-center gap-2 border border-white/15 px-4 text-[9px] tracking-[.18em] text-white/60 hover:border-gold hover:text-gold disabled:opacity-30"><LinkIcon size={13}/> USE LINK</button></div>
   {error&&<p className="mt-3 text-[10px] text-red-300">{error}</p>}
   <div className="mt-5 space-y-2">{results.map(r=><button key={r.id} onClick={()=>setSelected(r)} className="flex w-full gap-3 border border-white/10 p-3 text-left hover:border-gold/50 hover:bg-white/[.03]"><img src={r.thumbnail} alt="" className="h-14 w-24 object-cover"/><div className="min-w-0 flex-1"><p className="truncate text-sm">{r.title}</p><p className="mt-1 text-[10px] text-white/35">{r.channel}</p></div><Plus size={15} className="mt-2 shrink-0 text-gold"/></button>)}</div>
   {!results.length&&!loading&&<div className="py-8 text-center text-xs text-white/20">Search YouTube or paste a link to recommend a song.</div>}
  </div>
  <div className="glass p-6 md:p-8"><div className="flex items-center justify-between"><span className="text-[9px] tracking-[.35em] text-white/35">RECOMMENDED BY THE ROOM</span><span className="text-[9px] text-gold">LIVE</span></div><div className="mt-5 space-y-3">{items.map(i=><div key={i.id} className="border border-white/10 p-4"><div className="flex gap-3"><img src={i.thumbnail} alt="" className="h-12 w-20 object-cover"/><div className="min-w-0 flex-1"><p className="truncate text-sm">{i.title}</p><p className="text-[9px] text-white/35">{i.channel} · recommended by <span className="text-gold">{i.username}</span></p></div><a href={`https://www.youtube.com/watch?v=${i.youtube_id}`} target="_blank" rel="noreferrer" className="text-white/30 hover:text-gold"><Play size={15}/></a></div><p className="mt-3 text-xs leading-5 text-white/50">{i.comment}</p>{i.end_seconds>i.start_seconds&&<p className="mt-2 flex items-center gap-1 text-[9px] text-gold"><Clock3 size={11}/> {i.start_seconds}s → {i.end_seconds}s</p>}</div>)}{!items.length&&<p className="py-10 text-center text-xs text-white/20">No recommendations yet. Be the first.</p>}</div></div>
  {selected&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/85 p-5 backdrop-blur-md"><div className="glass max-h-[90vh] w-full max-w-xl overflow-auto p-6 md:p-8"><div className="flex justify-between gap-4"><div className="flex gap-3"><img src={selected.thumbnail} alt="" className="h-16 w-28 object-cover"/><div><p className="text-sm font-semibold">{selected.title}</p><p className="mt-1 text-[10px] text-white/35">{selected.channel}</p></div></div><button onClick={()=>setSelected(null)}><X size={18} className="text-white/40"/></button></div><label className="mt-6 block text-[9px] tracking-[.25em] text-white/35">YOUR USERNAME<input value={name} onChange={e=>setName(e.target.value)} maxLength={24} placeholder="pranav998" className="mt-2 w-full border border-white/10 bg-transparent p-3 text-sm outline-none focus:border-gold"/></label><label className="mt-5 block text-[9px] tracking-[.25em] text-white/35">YOUR RECOMMENDATION / MESSAGE<textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={1000} placeholder="Geetqar, you should hear this…" className="mt-2 min-h-28 w-full resize-none border border-white/10 bg-transparent p-3 text-sm outline-none focus:border-gold"/></label><div className="mt-5 grid grid-cols-2 gap-3"><label className="text-[9px] tracking-[.2em] text-white/35">START (SECONDS)<input value={start} onChange={e=>setStart(e.target.value)} inputMode="numeric" placeholder="0" className="mt-2 w-full border border-white/10 bg-transparent p-3 text-sm outline-none focus:border-gold"/></label><label className="text-[9px] tracking-[.2em] text-white/35">END (SECONDS)<input value={end} onChange={e=>setEnd(e.target.value)} inputMode="numeric" placeholder="30" className="mt-2 w-full border border-white/10 bg-transparent p-3 text-sm outline-none focus:border-gold"/></label></div><button onClick={save} disabled={saving||name.trim().length<2||!comment.trim()} className="mt-6 flex w-full items-center justify-center gap-2 border border-gold/40 px-5 py-3 text-[10px] tracking-[.25em] text-gold hover:bg-gold hover:text-black disabled:opacity-30">{saving?<Loader2 size={15} className="animate-spin"/>:<Plus size={15}/>} RECOMMEND THIS SONG</button></div></div>}
 </div>
}
